import { Project } from "@/types/project";
import { Property } from "@/types/property";
import { Payment, PaymentPlan } from "@/types/Payment";

// Helper function to create payment plans
const createPaymentPlan = (totalAmount: number, firstPaymentPercentage: number = 30): PaymentPlan => {
  const firstPaymentAmount = (totalAmount * firstPaymentPercentage) / 100;
  const remainingAmount = totalAmount - firstPaymentAmount;
  const monthlyPayment = remainingAmount / 11; // 12 months total, first payment already done

  const payments: Payment[] = Array.from({ length: 12 }, (_, index) => ({
    id: index + 1,
    amount: index === 0 ? firstPaymentAmount : monthlyPayment,
    dueDate: new Date(Date.now() + index * 30 * 24 * 60 * 60 * 1000), // 30 days apart
    status: (index === 0 ? "PAID" : "PENDING") as "PAID" | "PENDING" | "LATE",
    property: {} as Property, // Will be set when creating properties
    createdAt: new Date(),
    updatedAt: new Date(),
    isFirstPayment: index === 0,
    percentageOfTotal: index === 0 ? firstPaymentPercentage : (monthlyPayment / totalAmount) * 100,
  }));

  return {
    payments,
    totalAmount,
    firstPaymentAmount,
    firstPaymentPercentage,
    isValid: true,
    validationErrors: [],
  };
};

export const dummyProjects: Project[] = [
  // Project 1: Completed Project (Done)
  {
    id: 1,
    name: "Résidence Atlas",
    numberOfProperties: 50,
    totalSurface: 5000,
    address: "Casablanca, Quartier Maarif",
    latitude: 33.5731,
    longitude: -7.5898,
    folderFees: 15000,
    totalSales: 45,
    status: "done",
    progress: 100,
    image: null,
    constructionPhotos: [],
    notes: "Projet résidentiel de luxe avec vue sur la mer",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-06-15"),
    lastUpdate: "2024-06-15",
    statusDates: {
      planification: "2023-01-15",
      construction: "2023-03-01",
      done: "2024-06-15",
    },
    properties: [
      {
        id: 1,
        number: "A-101",
        type: "APARTMENT",
        status: "SOLD",
        floor: 1,
        zone: "Zone A",
        habitable: 85,
        balcon: 12,
        terrasse: 0,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1168750,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-05-20"),
        payments: createPaymentPlan(1168750),
      },
      {
        id: 2,
        number: "A-102",
        type: "APARTMENT",
        status: "SOLD",
        floor: 1,
        zone: "Zone A",
        habitable: 95,
        balcon: 15,
        terrasse: 0,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1306250,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 150000,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-05-25"),
        payments: createPaymentPlan(1456250), // Including parking
      },
      {
        id: 3,
        number: "V-201",
        type: "VILLA",
        status: "RESERVED",
        floor: 2,
        zone: "Zone B",
        habitable: 200,
        balcon: 0,
        terrasse: 50,
        piscine: 25,
        prixType: "FIXE",
        prixTotal: 3500000,
        commissionPerM2: 500,
        prixPiscine: 8000,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-10"),
        payments: createPaymentPlan(3500000),
      },
    ],
  },

  // Project 2: Under Construction
  {
    id: 2,
    name: "Ocean View Residence",
    numberOfProperties: 80,
    totalSurface: 8000,
    address: "Mohammedia, Corniche",
    latitude: 33.6861,
    longitude: -7.3829,
    folderFees: 20000,
    totalSales: 35,
    status: "construction",
    progress: 75,
    image: null,
    constructionPhotos: [],
    notes: "Résidence avec vue panoramique sur l'océan",
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-06-20"),
    lastUpdate: "2024-06-20",
    statusDates: {
      planification: "2023-06-01",
      construction: "2023-09-15",
    },
    properties: [
      {
        id: 4,
        number: "B-101",
        type: "DUPLEX",
        status: "SOLD",
        floor: 1,
        zone: "Zone C",
        habitable: 120,
        balcon: 20,
        terrasse: 30,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1650000,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-04-15"),
        payments: createPaymentPlan(1650000),
      },
      {
        id: 5,
        number: "B-102",
        type: "APARTMENT",
        status: "AVAILABLE",
        floor: 1,
        zone: "Zone C",
        habitable: 75,
        balcon: 10,
        terrasse: 0,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1031250,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 120000,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(1151250),
      },
      {
        id: 6,
        number: "S-001",
        type: "STORE",
        status: "AVAILABLE",
        floor: 0,
        zone: "Zone Commerciale",
        totalArea: 150,
        mezzanineArea: 50,
        mezzaninePrice: 500000,
        prixType: "FIXE",
        prixTotal: 2500000,
        commissionPerM2: 800,
        parkingDisponible: false,
        parkingInclus: false,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(3000000), // Including mezzanine
      },
    ],
  },

  // Project 3: Planning Phase
  {
    id: 3,
    name: "Business Plaza",
    numberOfProperties: 30,
    totalSurface: 3000,
    address: "Rabat, Agdal",
    latitude: 34.0209,
    longitude: -6.8416,
    folderFees: 25000,
    totalSales: 0,
    status: "planification",
    progress: 25,
    image: null,
    constructionPhotos: [],
    notes: "Centre d'affaires moderne avec bureaux et commerces",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-06-20"),
    lastUpdate: "2024-06-20",
    statusDates: {
      planification: "2024-01-01",
    },
    properties: [
      {
        id: 7,
        number: "C-101",
        type: "STORE",
        status: "AVAILABLE",
        floor: 0,
        zone: "Zone Commerciale",
        totalArea: 200,
        mezzanineArea: 80,
        mezzaninePrice: 800000,
        prixType: "M2",
        prixTotal: 4000000,
        prixM2: 20000,
        commissionPerM2: 1000,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 200000,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(5000000), // Including mezzanine and parking
      },
      {
        id: 8,
        number: "L-001",
        type: "LAND",
        status: "AVAILABLE",
        zone: "Zone Terrain",
        totalArea: 500,
        prixType: "FIXE",
        prixTotal: 1500000,
        commissionPerM2: 3000,
        parkingDisponible: false,
        parkingInclus: false,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(1500000),
      },
    ],
  },

  // Project 4: Mixed Status Project
  {
    id: 4,
    name: "Garden Residence",
    numberOfProperties: 120,
    totalSurface: 15000,
    address: "Marrakech, Palmeraie",
    latitude: 31.6295,
    longitude: -7.9811,
    folderFees: 18000,
    totalSales: 65,
    status: "construction",
    progress: 60,
    image: null,
    constructionPhotos: [],
    notes: "Résidence écologique avec jardins et espaces verts",
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-06-20"),
    lastUpdate: "2024-06-20",
    statusDates: {
      planification: "2023-03-15",
      construction: "2023-07-01",
    },
    properties: [
      {
        id: 9,
        number: "D-101",
        type: "VILLA",
        status: "SOLD",
        floor: 1,
        zone: "Zone D",
        habitable: 180,
        balcon: 0,
        terrasse: 60,
        piscine: 30,
        prixType: "FIXE",
        prixTotal: 4200000,
        commissionPerM2: 600,
        prixPiscine: 10000,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-03-20"),
        payments: createPaymentPlan(4200000),
      },
      {
        id: 10,
        number: "D-102",
        type: "APARTMENT",
        status: "RESERVED",
        floor: 2,
        zone: "Zone D",
        habitable: 90,
        balcon: 15,
        terrasse: 0,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1237500,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 100000,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-15"),
        payments: createPaymentPlan(1337500),
      },
      {
        id: 11,
        number: "D-103",
        type: "DUPLEX",
        status: "AVAILABLE",
        floor: 3,
        zone: "Zone D",
        habitable: 140,
        balcon: 25,
        terrasse: 40,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1925000,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(1925000),
      },
    ],
  },

  // Project 5: Luxury Project
  {
    id: 5,
    name: "Luxury Towers",
    numberOfProperties: 200,
    totalSurface: 25000,
    address: "Casablanca, Anfa",
    latitude: 33.5952,
    longitude: -7.6324,
    folderFees: 30000,
    totalSales: 25,
    status: "planification",
    progress: 15,
    image: null,
    constructionPhotos: [],
    notes: "Tours de luxe avec services haut de gamme",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-20"),
    lastUpdate: "2024-06-20",
    statusDates: {
      planification: "2024-02-01",
    },
    properties: [
      {
        id: 12,
        number: "E-101",
        type: "VILLA",
        status: "SOLD",
        floor: 1,
        zone: "Zone E",
        habitable: 250,
        balcon: 0,
        terrasse: 80,
        piscine: 40,
        prixType: "FIXE",
        prixTotal: 8000000,
        commissionPerM2: 1000,
        prixPiscine: 15000,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-05-10"),
        payments: createPaymentPlan(8000000),
      },
      {
        id: 13,
        number: "E-102",
        type: "APARTMENT",
        status: "AVAILABLE",
        floor: 15,
        zone: "Zone E",
        habitable: 120,
        balcon: 20,
        terrasse: 0,
        piscine: 0,
        prixType: "M2",
        prixTotal: 1650000,
        prixM2: 13750,
        prixBalconPct: 50,
        prixTerrassePct: 75,
        parkingDisponible: true,
        parkingInclus: true,
        prixParking: 0,
        project: {} as Project,
        client: null,
        updatedAt: new Date("2024-06-01"),
        payments: createPaymentPlan(1650000),
      },
    ],
  },
];

// Set the project reference for each property
dummyProjects.forEach(project => {
  if (project.properties) {
    project.properties.forEach(property => {
      property.project = project;
    });
  }
});