import { Contract } from "@/types/Contract";
import { Role, Status } from "@/types/user";

export const dummyContracts: Contract[] = [
    {
      id: 1,
      template: {
        id: 1,
        name: 'Contrat de Réservation Standard',
        description: 'Template standard pour la réservation d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        assignedProjects: [],
        isDefault: true,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 1,
        name: 'Fatima Alami',
        firstName: 'Fatima',
        lastName: 'Alami',
        email: 'fatima.alami@email.com',
        phoneNumber: '+212612345678',
        whatsappNumber: '+212612345678',
        provenance: 'Website',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Carte d\'identité',
        identityNumber: 'AB123456',
      },
      property: {
        id: 1,
        number: 'A101',
        project: {
          id: 1,
          name: 'Résidence Les Palmiers',
          address: 'Avenue Mohammed V, Casablanca',
          numberOfProperties: 120,
          totalSurface: 15000,
          latitude: 33.5731,
          longitude: -7.5898,
          folderFees: 15000,
          status: "construction",
          progress: 65,
        },
        floor: 1,
        type: 'APARTMENT',
        status: 'RESERVED',
        zone: 'Zone A',
        habitable: 85,
        balcon: 12,
        terrasse: 0,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 850000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'WAITING_CVALIDATION',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
    },
    {
      id: 2,
      template: {
        id: 2,
        name: 'Contrat de Vente Définitif',
        description: 'Template pour la vente définitive d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 2,
        name: 'Karim Mansouri',
        firstName: 'Karim',
        lastName: 'Mansouri',
        email: 'karim.mansouri@email.com',
        phoneNumber: '+212623456789',
        whatsappNumber: '+212623456789',
        provenance: 'Referral',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Passport',
        identityNumber: 'P123456789',
      },
      property: {
        id: 2,
        number: 'B205',
        project: {
          id: 2,
          name: 'Tours Marina',
          address: 'Boulevard de la Corniche, Casablanca',
          numberOfProperties: 85,
          totalSurface: 12000,
          latitude: 33.5779,
          longitude: -7.5911,
          folderFees: 20000,
          status: "construction",
          progress: 80,
        },
        floor: 2,
        type: 'DUPLEX',
        status: 'SOLD',
        zone: 'Zone B',
        habitable: 120,
        balcon: 15,
        terrasse: 25,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 1200000,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 150000,
      },
      status: 'VALIDATED_BY_CLIENT',
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      id: 3,
      template: {
        id: 1,
        name: 'Contrat de Réservation Standard',
        description: 'Template standard pour la réservation d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        assignedProjects: [],
        isDefault: true,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 3,
        name: 'Amina Tazi',
        firstName: 'Amina',
        lastName: 'Tazi',
        email: 'amina.tazi@email.com',
        phoneNumber: '+212634567890',
        whatsappNumber: '+212634567890',
        provenance: 'Social Media',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Carte d\'identité',
        identityNumber: 'CD789012',
      },
      property: {
        id: 3,
        number: 'C301',
        project: {
          id: 3,
          name: 'Résidence Al Andalous',
          address: 'Quartier Maarif, Casablanca',
          numberOfProperties: 65,
          totalSurface: 8000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 12000,
          status: "done",
          progress: 100,
        },
        floor: 3,
        type: 'APARTMENT',
        status: 'SOLD',
        zone: 'Zone C',
        habitable: 95,
        balcon: 10,
        terrasse: 0,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 950000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'LEGALIZED',
      createdAt: new Date('2023-12-15'),
      updatedAt: new Date('2024-01-10'),
    },
    {
      id: 4,
      template: {
        id: 3,
        name: 'Contrat de Location',
        description: 'Template pour la location d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-08'),
        updatedAt: new Date('2024-01-08'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 2,
          name: 'Sara El Fassi',
          email: 'sara.elfassi@immo360.ma',
          phoneNumber: '+212645678901',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 4,
        name: 'Hassan Berrada',
        firstName: 'Hassan',
        lastName: 'Berrada',
        email: 'hassan.berrada@email.com',
        phoneNumber: '+212656789012',
        whatsappNumber: '+212656789012',
        provenance: 'Website',
        status: 'CLIENT',
        createdById: 2,
        identityType: 'Carte d\'identité',
        identityNumber: 'EF345678',
      },
      property: {
        id: 4,
        number: 'D401',
        project: {
          id: 4,
          name: 'Les Jardins de l\'Atlas',
          address: 'Route d\'El Jadida, Casablanca',
          numberOfProperties: 95,
          totalSurface: 18000,
          latitude: 33.5589,
          longitude: -7.6324,
          folderFees: 18000,
          status: "planification",
          progress: 15,
        },
        floor: 4,
        type: 'VILLA',
        status: 'RESERVED',
        zone: 'Zone D',
        habitable: 180,
        balcon: 0,
        terrasse: 50,
        piscine: 20,
        prixType: 'FIXE',
        prixTotal: 2500000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'WAITING_CVALIDATION',
      createdAt: new Date('2024-01-25'),
      updatedAt: new Date('2024-01-25'),
    },
    {
      id: 5,
      template: {
        id: 2,
        name: 'Contrat de Vente Définitif',
        description: 'Template pour la vente définitive d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 5,
        name: 'Leila Benjelloun',
        firstName: 'Leila',
        lastName: 'Benjelloun',
        email: 'leila.benjelloun@email.com',
        phoneNumber: '+212667890123',
        whatsappNumber: '+212667890123',
        provenance: 'Referral',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Passport',
        identityNumber: 'P987654321',
      },
      property: {
        id: 5,
        number: 'E501',
        project: {
          id: 5,
          name: 'Oasis Golf City',
          address: 'Route de Bouskoura, Casablanca',
          numberOfProperties: 150,
          totalSurface: 25000,
          latitude: 33.5589,
          longitude: -7.6324,
          folderFees: 25000,
          status: "construction",
          progress: 45,
        },
        floor: 5,
        type: 'APARTMENT',
        status: 'SOLD',
        zone: 'Zone E',
        habitable: 110,
        balcon: 12,
        terrasse: 0,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 1100000,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 120000,
      },
      status: 'VALIDATED',
      createdAt: new Date('2023-11-20'),
      updatedAt: new Date('2024-01-05'),
    },
    {
      id: 6,
      template: {
        id: 1,
        name: 'Contrat de Réservation Standard',
        description: 'Template standard pour la réservation d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        assignedProjects: [],
        isDefault: true,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 6,
        name: 'Youssef Idrissi',
        firstName: 'Youssef',
        lastName: 'Idrissi',
        email: 'youssef.idrissi@email.com',
        phoneNumber: '+212678901234',
        whatsappNumber: '+212678901234',
        provenance: 'Website',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Carte d\'identité',
        identityNumber: 'GH567890',
      },
      property: {
        id: 6,
        number: 'F601',
        project: {
          id: 6,
          name: 'Résidence Le Dôme',
          address: 'Avenue Hassan II, Casablanca',
          numberOfProperties: 75,
          totalSurface: 10000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 16000,
          status: "construction",
          progress: 70,
        },
        floor: 6,
        type: 'DUPLEX',
        status: 'RESERVED',
        zone: 'Zone F',
        habitable: 140,
        balcon: 18,
        terrasse: 30,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 1400000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'WAITING_CVALIDATION',
      createdAt: new Date('2024-01-28'),
      updatedAt: new Date('2024-01-28'),
    },
    {
      id: 7,
      template: {
        id: 2,
        name: 'Contrat de Vente Définitif',
        description: 'Template pour la vente définitive d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 7,
        name: 'Nadia El Khoury',
        firstName: 'Nadia',
        lastName: 'El Khoury',
        email: 'nadia.elkhoury@email.com',
        phoneNumber: '+212689012345',
        whatsappNumber: '+212689012345',
        provenance: 'Social Media',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Passport',
        identityNumber: 'P456789123',
      },
      property: {
        id: 7,
        number: 'G701',
        project: {
          id: 7,
          name: 'Les Terrasses du Port',
          address: 'Port de Casablanca',
          numberOfProperties: 60,
          totalSurface: 9000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 22000,
          status: "done",
          progress: 100,
        },
        floor: 7,
        type: 'APARTMENT',
        status: 'SOLD',
        zone: 'Zone G',
        habitable: 90,
        balcon: 15,
        terrasse: 0,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 1350000,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 180000,
      },
      status: 'LEGALIZED',
      createdAt: new Date('2023-10-15'),
      updatedAt: new Date('2023-12-20'),
    },
    {
      id: 8,
      template: {
        id: 1,
        name: 'Contrat de Réservation Standard',
        description: 'Template standard pour la réservation d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        assignedProjects: [],
        isDefault: true,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 8,
        name: 'Rachid Benchekroun',
        firstName: 'Rachid',
        lastName: 'Benchekroun',
        email: 'rachid.benchekroun@email.com',
        phoneNumber: '+212690123456',
        whatsappNumber: '+212690123456',
        provenance: 'Website',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Carte d\'identité',
        identityNumber: 'IJ901234',
      },
      property: {
        id: 8,
        number: 'H801',
        project: {
          id: 8,
          name: 'Résidence Les Oliviers',
          address: 'Ain Diab, Casablanca',
          numberOfProperties: 85,
          totalSurface: 11000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 14000,
          status: "construction",
          progress: 55,
        },
        floor: 8,
        type: 'VILLA',
        status: 'RESERVED',
        zone: 'Zone H',
        habitable: 200,
        balcon: 0,
        terrasse: 60,
        piscine: 25,
        prixType: 'FIXE',
        prixTotal: 2800000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'VALIDATED_BY_CLIENT',
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-01-22'),
    },
    {
      id: 9,
      template: {
        id: 3,
        name: 'Contrat de Location',
        description: 'Template pour la location d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-08'),
        updatedAt: new Date('2024-01-08'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 2,
          name: 'Sara El Fassi',
          email: 'sara.elfassi@immo360.ma',
          phoneNumber: '+212645678901',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 9,
        name: 'Samira Bennis',
        firstName: 'Samira',
        lastName: 'Bennis',
        email: 'samira.bennis@email.com',
        phoneNumber: '+212601234567',
        whatsappNumber: '+212601234567',
        provenance: 'Referral',
        status: 'CLIENT',
        createdById: 2,
        identityType: 'Carte d\'identité',
        identityNumber: 'KL123456',
      },
      property: {
        id: 9,
        number: 'I901',
        project: {
          id: 9,
          name: 'Les Jardins de Sidi Abderrahmane',
          address: 'Sidi Abderrahmane, Casablanca',
          numberOfProperties: 110,
          totalSurface: 16000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 17000,
          status: "planification",
          progress: 25,
        },
        floor: 9,
        type: 'APARTMENT',
        status: 'RESERVED',
        zone: 'Zone I',
        habitable: 75,
        balcon: 8,
        terrasse: 0,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 750000,
        parkingDisponible: true,
        parkingInclus: true,
      },
      status: 'WAITING_CVALIDATION',
      createdAt: new Date('2024-01-30'),
      updatedAt: new Date('2024-01-30'),
    },
    {
      id: 10,
      template: {
        id: 2,
        name: 'Contrat de Vente Définitif',
        description: 'Template pour la vente définitive d\'appartements',
        content: 'Template content here',
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        assignedProjects: [],
        isDefault: false,
        createdBy: {
          id: 1,
          name: 'Ahmed Benali',
          email: 'ahmed.benali@immo360.ma',
          phoneNumber: '+212661234567',
          role: Role.ADMIN,
          status: Status.ACTIVE,
          passwordHash: 'password',
        },
      },
      client: {
        id: 10,
        name: 'Mohammed El Amrani',
        firstName: 'Mohammed',
        lastName: 'El Amrani',
        email: 'mohammed.elamrani@email.com',
        phoneNumber: '+212612345678',
        whatsappNumber: '+212612345678',
        provenance: 'Website',
        status: 'CLIENT',
        createdById: 1,
        identityType: 'Passport',
        identityNumber: 'P789123456',
      },
      property: {
        id: 10,
        number: 'J1001',
        project: {
          id: 10,
          name: 'Résidence Le Phare',
          address: 'Ain Sebaa, Casablanca',
          numberOfProperties: 95,
          totalSurface: 13000,
          latitude: 33.5951,
          longitude: -7.6324,
          folderFees: 15000,
          status: "construction",
          progress: 85,
        },
        floor: 10,
        type: 'DUPLEX',
        status: 'SOLD',
        zone: 'Zone J',
        habitable: 160,
        balcon: 20,
        terrasse: 35,
        piscine: 0,
        prixType: 'FIXE',
        prixTotal: 1600000,
        parkingDisponible: true,
        parkingInclus: false,
        prixParking: 150000,
      },
      status: 'VALIDATED',
      createdAt: new Date('2023-09-10'),
      updatedAt: new Date('2023-12-15'),
    }
  ]
    
  // ... existing code ...