import { Payment } from "@/types/Payment";
import { Role, Status } from "@/types/user";

export const dummyPayments: Payment[] = [
    {
      id: 1,
      amount: 100000,
      dueDate: new Date(),
      status: 'LATE',
      proofOfPayment: null,
      contract: {
        id: 1,
        template: {
          id: 1,
          name: 'Template 1',
          description: 'Description 1',
          content: 'Content 1',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 1,
            name: 'User 1',
            email: 'user1@gmail.com',
            phoneNumber: '0600000000',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 1,
          firstName: 'John',
          lastName: 'Doe',
          email: 'john.doe@example.com',
          phoneNumber: '+1234567890',
          provenance: 'Client 1',
          status: 'CLIENT',
          name: 'Client 1',
          createdById: 1,
          payments: []
        },
        property: {
          id: 1,
          number: '1',
          project: {
            id: 1,
            name: 'Project 1',
            address: 'Address 1',
            totalSurface: 100,
            commissionPerM2: 1000,
            progress: 10,
            status: 'planification',
            numberOfProperties: 10,
            latitude: 10.0,
            longitude: 10.0,
            folderFees: 1000,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 1,
          type: 'APARTMENT',
          prixTotal: 100000,
          prixM2: 1000,
          zone: 'Zone A',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 1,
        number: '1',
        project: {
          id: 1,
          name: 'Project 1',
          address: 'Address 1',
          totalSurface: 100,
          commissionPerM2: 1000,
          progress: 10,
          status: 'planification',
          numberOfProperties: 10,
          latitude: 10.0,
          longitude: 10.0,
          folderFees: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 1,
        type: 'APARTMENT',
        prixTotal: 100000,
        prixM2: 1000,
        zone: 'Zone A',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 2,
      amount: 75000,
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
      status: 'PENDING',
      proofOfPayment: null,
      contract: {
        id: 2,
        template: {
          id: 2,
          name: 'Template 2',
          description: 'Description 2',
          content: 'Content 2',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 2,
            name: 'User 2',
            email: 'user2@gmail.com',
            phoneNumber: '0600000001',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 2,
          firstName: 'Jane',
          lastName: 'Smith',
          email: 'jane.smith@example.com',
          phoneNumber: '+1234567891',
          provenance: 'Client 2',
          status: 'CLIENT',
          name: 'Client 2',
          createdById: 2,
          payments: []
        },
        property: {
          id: 2,
          number: '2',
          project: {
            id: 2,
            name: 'Project 2',
            address: 'Address 2',
            totalSurface: 150,
            commissionPerM2: 1200,
            progress: 25,
            status: 'construction',
            numberOfProperties: 15,
            latitude: 11.0,
            longitude: 11.0,
            folderFees: 1200,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 2,
          type: 'APARTMENT',
          prixTotal: 75000,
          prixM2: 1200,
          zone: 'Zone B',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 2,
        number: '2',
        project: {
          id: 2,
          name: 'Project 2',
          address: 'Address 2',
          totalSurface: 150,
          commissionPerM2: 1200,
          progress: 25,
          status: 'construction',
          numberOfProperties: 15,
          latitude: 11.0,
          longitude: 11.0,
          folderFees: 1200,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 2,
        type: 'APARTMENT',
        prixTotal: 75000,
        prixM2: 1200,
        zone: 'Zone B',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 3,
      amount: 120000,
      dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      status: 'PAID',
      proofOfPayment: null,
      contract: {
        id: 3,
        template: {
          id: 3,
          name: 'Template 3',
          description: 'Description 3',
          content: 'Content 3',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 3,
            name: 'User 3',
            email: 'user3@gmail.com',
            phoneNumber: '0600000002',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 3,
          firstName: 'Mike',
          lastName: 'Johnson',
          email: 'mike.johnson@example.com',
          phoneNumber: '+1234567892',
          provenance: 'Client 3',
          status: 'CLIENT',
          name: 'Client 3',
          createdById: 3,
          payments: []
        },
        property: {
          id: 3,
          number: '3',
          project: {
            id: 3,
            name: 'Project 3',
            address: 'Address 3',
            totalSurface: 200,
            commissionPerM2: 1500,
            progress: 50,
            status: 'done',
            numberOfProperties: 20,
            latitude: 12.0,
            longitude: 12.0,
            folderFees: 1500,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 3,
          type: 'VILLA',
          prixTotal: 120000,
          prixM2: 1500,
          zone: 'Zone C',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 3,
        number: '3',
        project: {
          id: 3,
          name: 'Project 3',
          address: 'Address 3',
          totalSurface: 200,
          commissionPerM2: 1500,
          progress: 50,
        status: 'done',
          numberOfProperties: 20,
          latitude: 12.0,
          longitude: 12.0,
          folderFees: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 3,
        type: 'VILLA',
        prixTotal: 120000,
        prixM2: 1500,
        zone: 'Zone C',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 4,
      amount: 85000,
      dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
      status: 'PENDING',
      proofOfPayment: null,
      contract: {
        id: 4,
        template: {
          id: 4,
          name: 'Template 4',
          description: 'Description 4',
          content: 'Content 4',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 4,
            name: 'User 4',
            email: 'user4@gmail.com',
            phoneNumber: '0600000003',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 4,
          firstName: 'Sarah',
          lastName: 'Wilson',
          email: 'sarah.wilson@example.com',
          phoneNumber: '+1234567893',
          provenance: 'Client 4',
          status: 'CLIENT',
          name: 'Client 4',
          createdById: 4,
          payments: []
        },
        property: {
          id: 4,
          number: '4',
          project: {
            id: 4,
            name: 'Project 4',
            address: 'Address 4',
            totalSurface: 120,
            commissionPerM2: 1100,
            progress: 30,
            status: 'construction',
            numberOfProperties: 12,
            latitude: 13.0,
            longitude: 13.0,
            folderFees: 1100,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 4,
          type: 'APARTMENT',
          prixTotal: 85000,
          prixM2: 1100,
          zone: 'Zone D',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 4,
        number: '4',
        project: {
          id: 4,
          name: 'Project 4',
          address: 'Address 4',
          totalSurface: 120,
          commissionPerM2: 1100,
          progress: 30,
          status: 'construction',
          numberOfProperties: 12,
          latitude: 13.0,
          longitude: 13.0,
          folderFees: 1100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 4,
        type: 'APARTMENT',
        prixTotal: 85000,
        prixM2: 1100,
        zone: 'Zone D',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 5,
      amount: 95000,
      dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
      status: 'LATE',
      proofOfPayment: null,
      contract: {
        id: 5,
        template: {
          id: 5,
          name: 'Template 5',
          description: 'Description 5',
          content: 'Content 5',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 5,
            name: 'User 5',
            email: 'user5@gmail.com',
            phoneNumber: '0600000004',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 5,
          firstName: 'David',
          lastName: 'Brown',
          email: 'david.brown@example.com',
          phoneNumber: '+1234567894',
          provenance: 'Client 5',
          status: 'CLIENT',
          name: 'Client 5',
          createdById: 5,
          payments: []
        },
        property: {
          id: 5,
          number: '5',
          project: {
            id: 5,
            name: 'Project 5',
            address: 'Address 5',
            totalSurface: 180,
            commissionPerM2: 1300,
            progress: 40,
            status: 'construction',
            numberOfProperties: 18,
            latitude: 14.0,
            longitude: 14.0,
            folderFees: 1300,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 5,
          type: 'VILLA',
          prixTotal: 95000,
          prixM2: 1300,
          zone: 'Zone E',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 5,
        number: '5',
        project: {
          id: 5,
          name: 'Project 5',
          address: 'Address 5',
          totalSurface: 180,
          commissionPerM2: 1300,
          progress: 40,
          status: 'construction',
          numberOfProperties: 18,
          latitude: 14.0,
          longitude: 14.0,
          folderFees: 1300,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 5,
        type: 'VILLA',
        prixTotal: 95000,
        prixM2: 1300,
        zone: 'Zone E',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 6,
      amount: 110000,
      dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000), // 21 days from now
      status: 'PENDING',
      proofOfPayment: null,
      contract: {
        id: 6,
        template: {
          id: 6,
          name: 'Template 6',
          description: 'Description 6',
          content: 'Content 6',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 6,
            name: 'User 6',
            email: 'user6@gmail.com',
            phoneNumber: '0600000005',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 6,
          firstName: 'Lisa',
          lastName: 'Davis',
          email: 'lisa.davis@example.com',
          phoneNumber: '+1234567895',
          provenance: 'Client 6',
          status: 'CLIENT',
          name: 'Client 6',
          createdById: 6,
          payments: []
        },
        property: {
          id: 6,
          number: '6',
          project: {
            id: 6,
            name: 'Project 6',
            address: 'Address 6',
            totalSurface: 160,
            commissionPerM2: 1400,
            progress: 60,
            status: 'construction',
            numberOfProperties: 16,
            latitude: 15.0,
            longitude: 15.0,
            folderFees: 1400,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 6,
          type: 'APARTMENT',
          prixTotal: 110000,
          prixM2: 1400,
          zone: 'Zone F',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 6,
        number: '6',
        project: {
          id: 6,
          name: 'Project 6',
          address: 'Address 6',
          totalSurface: 160,
          commissionPerM2: 1400,
          progress: 60,
          status: 'construction',
          numberOfProperties: 16,
          latitude: 15.0,
          longitude: 15.0,
          folderFees: 1400,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 6,
        type: 'APARTMENT',
        prixTotal: 110000,
        prixM2: 1400,
        zone: 'Zone F',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 7,
      amount: 130000,
      dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
      status: 'PAID',
      proofOfPayment: null,
      contract: {
        id: 7,
        template: {
          id: 7,
          name: 'Template 7',
          description: 'Description 7',
          content: 'Content 7',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 7,
            name: 'User 7',
            email: 'user7@gmail.com',
            phoneNumber: '0600000006',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 7,
          firstName: 'Robert',
          lastName: 'Miller',
          email: 'robert.miller@example.com',
          phoneNumber: '+1234567896',
          provenance: 'Client 7',
          status: 'CLIENT',
          name: 'Client 7',
          createdById: 7,
          payments: []
        },
        property: {
          id: 7,
          number: '7',
          project: {
            id: 7,
            name: 'Project 7',
            address: 'Address 7',
            totalSurface: 220,
            commissionPerM2: 1600,
            progress: 80,
            status: 'done',
            numberOfProperties: 22,
            latitude: 16.0,
            longitude: 16.0,
            folderFees: 1600,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 7,
          type: 'VILLA',
          prixTotal: 130000,
          prixM2: 1600,
          zone: 'Zone G',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 7,
        number: '7',
        project: {
          id: 7,
          name: 'Project 7',
          address: 'Address 7',
          totalSurface: 220,
          commissionPerM2: 1600,
          progress: 80,
          status: 'done',
          numberOfProperties: 22,
          latitude: 16.0,
          longitude: 16.0,
          folderFees: 1600,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 7,
        type: 'VILLA',
        prixTotal: 130000,
        prixM2: 1600,
        zone: 'Zone G',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 8,
      amount: 90000,
      dueDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000), // 28 days from now
      status: 'PENDING',
      proofOfPayment: null,
      contract: {
        id: 8,
        template: {
          id: 8,
          name: 'Template 8',
          description: 'Description 8',
          content: 'Content 8',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 8,
            name: 'User 8',
            email: 'user8@gmail.com',
            phoneNumber: '0600000007',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 8,
          firstName: 'Emma',
          lastName: 'Taylor',
          email: 'emma.taylor@example.com',
          phoneNumber: '+1234567897',
          provenance: 'Client 8',
          status: 'CLIENT',
          name: 'Client 8',
          createdById: 8,
          payments: []
        },
        property: {
          id: 8,
          number: '8',
          project: {
            id: 8,
            name: 'Project 8',
            address: 'Address 8',
            totalSurface: 140,
            commissionPerM2: 1250,
            progress: 35,
            status: 'construction',
            numberOfProperties: 14,
            latitude: 17.0,
            longitude: 17.0,
            folderFees: 1250,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 8,
          type: 'APARTMENT',
          prixTotal: 90000,
          prixM2: 1250,
          zone: 'Zone H',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 8,
        number: '8',
        project: {
          id: 8,
          name: 'Project 8',
          address: 'Address 8',
          totalSurface: 140,
          commissionPerM2: 1250,
          progress: 35,
          status: 'construction',
          numberOfProperties: 14,
          latitude: 17.0,
          longitude: 17.0,
          folderFees: 1250,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 8,
        type: 'APARTMENT',
        prixTotal: 90000,
        prixM2: 1250,
        zone: 'Zone H',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 9,
      amount: 105000,
      dueDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 days ago
      status: 'LATE',
      proofOfPayment: null,
      contract: {
        id: 9,
        template: {
          id: 9,
          name: 'Template 9',
          description: 'Description 9',
          content: 'Content 9',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 9,
            name: 'User 9',
            email: 'user9@gmail.com',
            phoneNumber: '0600000008',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 9,
          firstName: 'James',
          lastName: 'Anderson',
          email: 'james.anderson@example.com',
          phoneNumber: '+1234567898',
          provenance: 'Client 9',
          status: 'CLIENT',
          name: 'Client 9',
          createdById: 9,
          payments: []
        },
        property: {
          id: 9,
          number: '9',
          project: {
            id: 9,
            name: 'Project 9',
            address: 'Address 9',
            totalSurface: 190,
            commissionPerM2: 1350,
            progress: 45,
            status: 'construction',
            numberOfProperties: 19,
            latitude: 18.0,
            longitude: 18.0,
            folderFees: 1350,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 9,
          type: 'VILLA',
          prixTotal: 105000,
          prixM2: 1350,
          zone: 'Zone I',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 9,
        number: '9',
        project: {
          id: 9,
          name: 'Project 9',
          address: 'Address 9',
          totalSurface: 190,
          commissionPerM2: 1350,
          progress: 45,
          status: 'construction',
          numberOfProperties: 19,
          latitude: 18.0,
          longitude: 18.0,
          folderFees: 1350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 9,
        type: 'VILLA',
        prixTotal: 105000,
        prixM2: 1350,
        zone: 'Zone I',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: 10,
      amount: 115000,
      dueDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000), // 35 days from now
      status: 'PENDING',
      proofOfPayment: null,
      contract: {
        id: 10,
        template: {
          id: 10,
          name: 'Template 10',
          description: 'Description 10',
          content: 'Content 10',
          createdAt: new Date(),
          updatedAt: new Date(),
          assignedProjects: [],
          isDefault: false,
          createdBy: {
            id: 10,
            name: 'User 10',
            email: 'user10@gmail.com',
            phoneNumber: '0600000009',
            status: Status.ACTIVE,
            role: Role.ADMIN,
            passwordHash: 'password123'
          }
        },
        client: {
          id: 10,
          firstName: 'Maria',
          lastName: 'Garcia',
          email: 'maria.garcia@example.com',
          phoneNumber: '+1234567899',
          provenance: 'Client 10',
          status: 'CLIENT',
          name: 'Client 10',
          createdById: 10,
          payments: []
        },
        property: {
          id: 10,
          number: '10',
          project: {
            id: 10,
            name: 'Project 10',
            address: 'Address 10',
            totalSurface: 170,
            commissionPerM2: 1450,
            progress: 70,
            status: 'construction',
            numberOfProperties: 17,
            latitude: 19.0,
            longitude: 19.0,
            folderFees: 1450,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          floor: 10,
          type: 'APARTMENT',
          prixTotal: 115000,
          prixM2: 1450,
          zone: 'Zone J',
          status: 'AVAILABLE',
        },
        status: 'WAITING_CVALIDATION',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      property: {
        id: 10,
        number: '10',
        project: {
          id: 10,
          name: 'Project 10',
          address: 'Address 10',
          totalSurface: 170,
          commissionPerM2: 1450,
          progress: 70,
          status: 'construction',
          numberOfProperties: 17,
          latitude: 19.0,
          longitude: 19.0,
          folderFees: 1450,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        floor: 10,
        type: 'APARTMENT',
        prixTotal: 115000,
        prixM2: 1450,
        zone: 'Zone J',
        status: 'AVAILABLE',
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]
  
  // ... existing code ...